/' 共通設定 '/
hide footbox
hide circle
hide methods

/' 定数 '/
!define _PROJECT_CODE_ SampleProject
!define pk(x) <b>x</b>
!define fk(x) <u>x</u>
!define has_many(parent, children) parent ----{ children
!define title(x) title <size:20> x

/' スキン設定 '/
skinparam sequenceActorBorderColor #666666
skinparam sequenceActorBackgroundColor #ffe4e1
skinparam sequenceParticipantBorderColor #999999
skinparam sequenceParticipantBackgroundColor #ffe4e1
skinparam sequenceArrowColor #666666
skinparam sequenceLifeLineBorderColor #999999
skinparam sequenceBoxBorderColor #666666
skinparam noteBackgroundColor #ffffcc
skinparam noteBorderColor #999999
skinparam sequenceArrowColor #666666
skinparam shadowing false

skinparam class {
    HeaderBackgroundColor #F9FAFC
    FontColor black
    BackgroundColor white
    BorderColor black
}